### ISSUE TITLE
Some feeds do not work (version 2.3.0rc99)

### ISSUE THREAD

**Issue by thebat137** [ancestorak/brief#260]
I have a few feeds that have never worked properly with Brief.  In each case, the feed is able to be subscribed to, and it looks fine in my browser window, but Brief fails to find some or all of the feed entries.  When I put the feeds through the w3c feed validator at https://validator.w3.org/feed/check.cgi, some of them show imperfections, but it seems like these must be correctable, since at least some other feed readers can presumably handle these feeds.  The feeds in question are:

1. http://about.elsevier.com/media/MT_feed.xml
2. http://www.mnatheists.org/media/podcast/audio.xml
3. http://www.theskepticsguide.org/feed/rss.aspx?feed=sgu

Feed 1 does not show any entries at all in Brief.  Feed 2 shows the most recent entry, but older entries are not shown, and no entry ever comes up as "unread".  Feed 3 is rated as valid by the w3c tool and all older entries are shown in brief, but no entry ever comes up as unread and the most recent feed entry is not shown at all.

I'm not sure if these feeds are all having trouble for the same reasons, given the slightly different error modes, but hopefully someone more knowledgeable than I about how Brief parses feeds can determine this.

**Comment by tanriol** [comment]
Thank you for this report. Right now Brief still reuses the Firefox built-in feed parser and cannot probably do anything about this bug. However, the WebExtension version will be forced to introduce its own parser anyway and then this will be actionable.

**Comment by mailtowim** [comment]
You can subscribe to these podcast by first subscribing them with Firefox 'Live Bookmarks' in folder 'Bookmarks menu' > 'Subscribed Feeds'. For me this workaround worked for the podcasts of Разбор Полетов.

**Comment by mailtowim** [comment]
Possibly you also have to register 'application/vnd.mozilla.maybe.video.feed' and 'application/vnd.mozilla.maybe.audio.feed' to fix this in the code, rather than only application/vnd.mozilla.maybe.feed.

**Comment by thebat137** [comment]
@mailtowim, I am not sure how your suggestions address the problem I described in the original issue report.  The problem is not that Brief cannot subscribe to these feeds.  The problem is that, when they are subscribed to and appear in Brief, new feed entries are not detected by brief.

**Comment by mailtowim** [comment]
In Firefox Developer Edition 58, I cannot subscribe to podcasts. The solution was the above. 
Maybe you have to unsubscribe and subscribe again to these podcasts, so firefox sees them as podcasts, rather than regular feeds. 

I have 2 firefox installations (firefox and firefox developer edition.) I am using Brief 2.4 with Firefox Developer Edition. Brief 2.4 seems to be erroneously marked as incompatible with the Developer Edition but I installed it by using the xpi file. Right click in an regular version of firefox on the add button on https://addons.mozilla.org/en-US/firefox/addon/brief/. The resulting xpi file you can drop in a browser window of developer edition.
 
I also had an unrelated problem with refreshing in the developer edition, but I fixed it by emptying all tables in brief.sqlite (profile folder) with SQLite manager extension in regular firefox. It seems to refresh based on the bookmarks in 'Bookmarks menu' > 'Subscribed Feeds'. Also that extension doesn't work in the developer edition (no workaround).

It seems there are quite some bugs in the new version, but I got to workaround the bugs. I will upload tomorrow an 'empty' brief.sqlite file with which you can experiment and skip the step with SQlite manager extension. Ofcourse you better make a backup of your feed urls and brief.sqlite, before you start experimenting.

**Comment by thebat137** [comment]
@mailtowim, I'm still not sure what any of this has to do with the problem of Brief failing to *parse* feeds it is already subscribed to, which is the problem at the root of this bug report.  Can you explain that connection in a little more detali?

Alternately, there are other bug reports (such as issue #261 ) that address issues with subscribing to feeds; perhaps your experiences might be more closely related to one of those?

**Comment by silentbrains** [comment]
Using an up to date install of Firefox portable, a fresh brief.sqlite and disabling "Remove downloaded items after ___ days" in Brief, I was able to get this result with the feeds you linked:
![171109-15_53_49](https://user-images.githubusercontent.com/13858149/32636169-7b736d14-c568-11e7-8207-ef3cf4525326.jpg)
Additionally, other podcasts I've subscribed to via Live Bookmark have been working fine. 

This was just a test, I have no idea what the problem on your end might be. Since you first posted two months ago, you should've seen several new items from The Skeptics' Guide podcast, but it sounds like you haven't...

**Comment by thebat137** [comment]
@silentbrains, yes, what you describe is exactly what happens with that particular feed for me when I first subscribe to it. The problem is that new entries after the original subscription date are not detected properly.  That is why I say it is a parsing issue, not a subscription issue.  Also, the other feeds I listed have slightly different types of problems.

**Comment by silentbrains** [comment]
Understood, sorry for the misunderstanding!

**Comment by mailtowim** [comment]
For the Atheist Talk RSS, I can reproduce the problem. The channel XML element seems to be detected as a separate item on the RSS, while it should be skipped.

**Comment by thebat137** [comment]
That makes sense, @mailtowim. But I presume the parsing issues are actually with the built-in Firefox feed parser, as @tanriol says above, and so will be beyond the scope of readily available bug fixes until Brief switches to using it's own feed parser.

**Comment by mailtowim** [comment]
For the atheist talk rss it seems it is caused clearly by the Firefox feed parser, as for this feed, I see an error 'Live Bookmark failed to load'. The other 2 feeds seems to load fine in Firefox Developer Edition Quantum 58b1.

**Comment by bdcomp** [comment]
I have several feeds (manually added) not showing any item, just "No items" message.
For example:
https://codeascraft.com/feed/

An additional feed show only the last item.

All these feeds works great as Live Bookmarks.

Does it related to this issue or should I open a new one?

Brief 2.5.5
Firefox 57
Kubuntu 17.10 64bit

**Comment by tanriol** [comment]
@bdcomp I've just added the feed you referenced to my test profile and it successfully loaded 10 items. Are you sure you don't have the "remove items after N days" setting active?

**Comment by tanriol** [comment]
@thebat137 For the feeds you initially mentioned:
 - [Elsevier](http://about.elsevier.com/media/MT_feed.xml) has neither item IDs, nor item URLs. Brief for now considers item URLs mandatory, but I'll look how to remove that requirement in #316.
 - [Atheists Talk](http://www.mnatheists.org/media/podcast/audio.xml) is malformed as it does not escape characters that must be escaped in XML. At least for now this is a wontfix: I'm not going to introduce my own XML parser.
 - [The Skeptics Guide](http://www.theskepticsguide.org/feed/rss.aspx?feed=sgu) is a duplicate of #217 (the feed's "last modified" date is not updated when new items are added).

**Comment by mailtowim** [comment]
@bdcomp I have had that same issue. Afterwards I cleaned up my firefox profile and restarted from zero and the bug didn't return, but I did a backup with 'Export feeds' in Brief. 
I cannot reproduce the bug 'unfortunately' to find the cause.

**Comment by tanriol** [comment]
I'm closing this bug as there are no action items here and the parsing engine has significantly changed since it was opened. If there are other feeds that don't work, please search for existing bugs or open new ones.
